### ISSUE TITLE
CPU multiprocessing on Windows

### ISSUE THREAD

**Issue by NabJa** [marrlab/InstantDL#1]
In the code comments [(here)](https://github.com/marrlab/InstantDL/blob/master/instantdl/segmentation/RCNNmodel.py#L2368) the issue of multiprocessing on windows is already described. However, the `workers` are never passed to `keras_model.fit_generator` (see [here](https://github.com/marrlab/InstantDL/blob/master/instantdl/segmentation/RCNNmodel.py#L2376)).

Uncommenting the [line 2385](https://github.com/marrlab/InstantDL/blob/master/instantdl/segmentation/RCNNmodel.py#L2385) in the RCNNmodel solved the issue for me.

**Produced Errors:**
`Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in <lambda>
    initargs=(seqs, self.random_seed))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects`

**Relevant warnings:**
`INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.`

**Environment info:**

- Windows 10
- keras==2.2.4
- tensorflow==1.14
- Processor: intel(R) core(tm) i9‑9900k CPU @ 3.10 ghz

**Comment by aliechoes** [comment]
@DLMLDW can you please check that?

**Comment by DLMLDW** [comment]
Solved
